sudo: false

language: python

services: postgresql

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
    - DJANGO="1.10"
    - DJANGO="1.11"

# command to install dependencies
install:
    - pip install django==$DJANGO --quiet
    - pip install psycopg2 --quiet

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script:
    - python manage.py test
